---
- name : Ansible playbook to install a package 
  hosts: localhost 
  vars_files:
    - vars.yaml
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
