- name: SCP and copy script to {{ item }}
  command: scp  -o StrictHostKeyChecking=no  -o UserKnownHostsFile=/dev/null -i ibmkey {{ script_file_name }}  root@{{ item }}:/tmp
  register: output

- name: SSH and execute script on {{ item }}
  command: ssh   -o StrictHostKeyChecking=no  -o UserKnownHostsFile=/dev/null -i  ibmkey root@{{ item }} "sh /tmp/{{ script_file_name }} {{ args }}" >> /tmp/miq_conf_output.log 2>&1
  #timeout: 1000000
  register: output1
  ignore_errors: yes
  changed_when:
  - '"Connection to {{ item }} closed by remote host." in output1'

- name: Printing the output 
  debug : 
    msg: '{{ output1.stdout }}' 
