
- name: SCP  script file to host vm
  command: scp  -o StrictHostKeyChecking=no -i ibmkey {{ script_file_name }} root@{{ item }}:/tmp
      responses:
      (?i)password:  "{{ cfme_new_root_pw }}"
      (?i)root@localhost: exit
  register: output
  
- name: SSH and execute script
  vars: 
  expect:
    command: ssh   -o StrictHostKeyChecking=no -i  ./ibmkey root@{{ item }}
    timeout: 1000000
    responses:
      (?i)password:  "{{ cfme_new_root_pw }}"
      (?i)root@localhost: sh /tmp/"{{script_file_name}}"  {{ args }} && reboot  && exit
      #(?i)root@localhost: reboot  && exit
      #(?i)root@localhost: sh /tmp/"{{script_file_name}}"  "{{ hostname }}" "{{ miq_region }}" "{{ cfme_vpc_ip_range }}"  && exit
  register: output
  ignore_errors: yes
  changed_when:
  - '"Connection" in output.stdout'

- name: Printing the output 
  debug : 
    msg: '{{ output.stdout }}' 