- hosts: localhost
  vars_files:
      - group_vars/all/vars.yml
  tasks:
    - name: Change permission on private key file
      file:
        path: ibmkey
        state: file
        mode: u=r,g=-r,o=-r

    - include_tasks: reset-default-passwor.yml
      loop: "{{ query('inventory_hostnames', 'all') }}"

## ManageIQ master configuration
    - include_tasks: configure_miq_appliance.yml
      vars:
        script_file_name: configure_master_vmdb.sh
        args: "{{ hostvars[item].miq_appliance_hostname }}  {{ hostvars[item].cfme_master_region }} {{ cfme_vpc_ip_range }} {{ hostvars[item].replication_type }}  {{ hostvars[item].private_ip }}  {{ hostvars[item].miq_cluster_node_number }}  {{ cfme_db_user }} {{ cfme_db_pass }}"
      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}"

    - include_tasks: check_server_state.yml
      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}" 

    - include_tasks: configure_miq_appliance.yml
      vars:
        script_file_name: configure_appliance.sh
        args: "{{ hostvars[item].miq_appliance_hostname }}  {{ hostvars[item].vmdb_private_ip }}  {{ cfme_ssh_user }}  {{ cfme_new_root_pw }} {{ cfme_db_user }} {{ cfme_db_pass }}"
      loop: "{{ query('inventory_hostnames', 'master_primary_appliance') }}"

    - include_tasks: check_server_state.yml
      loop: "{{ query('inventory_hostnames', 'master_primary_appliance') }}" 

    - include_tasks: configure_miq_appliance.yml
      vars:
        script_file_name: configure_replication.sh
        args: "{{ hostvars[item].replication_type }}  {{ hostvars[item].private_ip }}  {{ hostvars[item].miq_cluster_node_number }}  {{ cfme_db_user }} {{ cfme_db_pass }}"
      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}" 

    - include_tasks: configure_miq_appliance.yml
      vars:
        script_file_name: configure_appliance_failover.sh
        args: "{{ hostvars[item].miq_appliance_hostname }}"
      loop: "{{ query('inventory_hostnames', 'master_primary_appliance') }}" 


## ManageIQ standby configuration
    - include_tasks: configure_miq_appliance.yml
      vars:
        args: "{{ hostvars[item].miq_appliance_hostname }}  {{ hostvars[item].cfme_master_region }}  {{ hostvars[item].replication_type }}  {{ hostvars[item].private_ip }}  {{ hostvars[item].miq_cluster_node_number }}  {{ cfme_db_user }} {{ cfme_db_pass }}  {{ hostvars[item].primary_host_ip }}  {{ cfme_ssh_user }} {{cfme_new_root_pw}} {{ hostvars[item].miq_db_disk }}"
        script_file_name: configure_vmdb.sh
      loop: "{{ query('inventory_hostnames', 'vmdb_appliance') }}" 

    - include_tasks: check_server_state.yml
      loop: "{{ query('inventory_hostnames', 'vmdb_appliance') }}" 

    - include_tasks: configure_miq_appliance.yml
      vars:
        args: "{{ hostvars[item].miq_appliance_hostname }}  {{ hostvars[item].vmdb_private_ip }}  {{ cfme_ssh_user }}  {{ cfme_new_root_pw }} {{ cfme_db_user }} {{ cfme_db_pass }}"
        script_file_name: configure_appliance.sh
      loop: "{{ query('inventory_hostnames', 'ui_appliance') }}"

    - include_tasks: check_server_state.yml
      loop: "{{ query('inventory_hostnames', 'ui_appliance') }}"

    - include_tasks: configure_miq_appliance.yml
      vars:
        script_file_name: configure_replication.sh
        args: "{{ hostvars[item].replication_type }}  {{ hostvars[item].private_ip }}  {{ hostvars[item].miq_cluster_node_number }}  {{ cfme_db_user }} {{ cfme_db_pass }} {{ hostvars[item].miq_db_disk }} {{ hostvars[item].primary_host_ip }}"
      loop: "{{ query('inventory_hostnames', 'vmdb_appliance') }}"

    - include_tasks: configure_miq_appliance.yml
      vars:
        script_file_name: configure_appliance_failover.sh
        args: "{{ hostvars[item].miq_appliance_hostname }}"
      loop: "{{ query('inventory_hostnames', 'ui_appliance') }}" 

## Check configuration status
    - include_tasks: configuration_status_check.yml
      loop: "{{ query('inventory_hostnames', 'all') }}"