---
- name: Create File
  gather_facts: no
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:

    - name: Create a virtual machine from a template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        folder: "/Test"
        name: mcmp-sept27-3
        state: poweredon
        template: CentOS6.6
        disk:
        - size_gb: 25
          type: thin
          autoselect_datastore: yes
        hardware:
          memory_mb: 1024
          num_cpus: 1
          scsi: paravirtual
        networks:
        - name: VM Network
          ip: 10.155.124.112
          netmask: 255.255.255.192
          device_type: vmxnet3
          domain: mcmpdomain
          gateway: 10.155.124.65
          dns_servers:
          - 10.154.23.131
          - 8.8.8.8          
        wait_for_ip_address: yes
        wait_for_ip_address_timeout: 60
      delegate_to: localhost
      register: deploy