---
- name: VM Based deployment step1
  hosts: localhost
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: configurations/group_vars/all/vars.yml

    - name: Add host to inventory vmdb
      add_host:
        name: 10.241.65.79
        private_ip: 10.241.65.79
        miq_appliance_hostname: auto-master-vmdb-01
        miq_cluster_node_number: 2
        cfme_master_region: 88
        groups: master_primary_db

    - name: Generate Auth token
      uri:
        url: "https://{{cfme_appliance}}/api/auth"
        method: GET
        user: "{{cfme_appliance_username}}"
        password: "{{cfme_appliance_password}}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
      register: manageiq

    - name: Get the credentials
      uri:
        url: "https://{{cfme_appliance}}/api/authentications?expand=resources&filter[]=name={{cfme_credential_name}}"
        method: GET
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.json.auth_token }}"
        body_format: json
        status_code: 200
      register: credential

    - name: Get the service catalog
      uri:
        url: "https://{{cfme_appliance}}/api/service_catalogs?expand=resources&filter[]=name={{cfme_catalog_name}}"
        method: GET
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.json.auth_token }}"
        body_format: json
        status_code: 200
      register: service_catalog

    - name: Save the service catalog id fact
      set_fact:
        cacheable: True
        service_catalog_id: "{{ service_catalog.json.resources[0].id}}"

    - name: Get the service template for vmdb
      uri:
        url: https://{{cfme_appliance}}/api/service_templates?expand=resources&filter[]=name={{cfme_vmdb_template_name}}
        method: GET
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.json.auth_token }}"
        body_format: json
        status_code: 200
      register: service_template

    - name: Save the service template id fact
      set_fact:
        cacheable: True
        service_template_id: "{{ service_template.json.resources[0].id}}"

    - name : Configure VMDB Appliances
      include_tasks: order_service.yml
      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}"

        
