# Ansible playbook that uses appliance_console_cli, plus existing
# Ansible modules, to provision a freshly deployed CloudForms manageIQ appliance.
#

# this play performs initial sysadmin for newly created CFME appliances
# we set a non-default root password, install a public key for ansible,

- hosts: master_primary_db
  become: yes
  vars:
    ansible_ssh_pass: bWFuYWdlaXE=
    ansible_user: root
    ansible_connection: ssh
  tasks:
    - name: Display Host name
      command: hostname
      register: hostnameMsg 
    
    - debug: msg="{{ hostnameMsg }}"
      
    - name: Create DIR
      command: mkdir /tmp/test12345
