- name: Appliance log file on {{ hostvars[item].miq_appliance_hostname }}
  command: ssh   -o StrictHostKeyChecking=no  -o UserKnownHostsFile=/dev/null -i  /tmp/{{ name_prefix }}-ssh_host_rsa_key root@{{ item }}  "cat /tmp/miq_conf_output.log"
  register: log_output