---
- name: Update host file
  hosts: localhost
  tasks:
    - name: Add the master primary vmdb appliance
      add_host:
        hostname: "{{item.private_ip}}"
        private_ip: "{{item.private_ip}}"
        miq_appliance_hostname: "{{item.miq_appliance_hostname}}"
        miq_cluster_node_number: "{{item.miq_cluster_node_number}}"
        primary_host_ip: "{{item.primary_host_ip}}"
        miq_region: "{{item.miq_region}}"
        replication_type: "{{item.replication_type}}"
        miq_db_disk: "{{ item.miq_db_disk }}"
        node: "{{ item.node }}"
        groups: [master_primary_db]
      loop: "{{master_primary_db}}"

    - name: Add the master primary ui appliance
      add_host:
        hostname: "{{item.private_ip}}"
        private_ip: "{{item.private_ip}}"
        miq_appliance_hostname: "{{item.miq_appliance_hostname}}"
        vmdb_private_ip: "{{ item.vmdb_private_ip }}"
        groups: [master_primary_appliance]
      loop: "{{master_primary_appliance}}"

    - name: Add the db appliances
      add_host:
        hostname: "{{item.private_ip}}"
        private_ip: "{{item.private_ip}}"
        miq_appliance_hostname: "{{item.miq_appliance_hostname}}"
        miq_cluster_node_number: "{{item.miq_cluster_node_number}}"
        primary_host_ip: "{{item.primary_host_ip}}"
        miq_region: "{{item.miq_region}}"
        replication_type: "{{item.replication_type}}"
        miq_db_disk: "{{ item.miq_db_disk }}"
        node: "{{ item.node }}"
        groups: [vmdb_appliance]
      loop: "{{vmdb_appliance}}"

    - name: Add the non db appliance
      add_host:
        hostname: "{{item.private_ip}}"
        private_ip: "{{item.private_ip}}"
        miq_appliance_hostname: "{{item.miq_appliance_hostname}}"
        vmdb_private_ip: "{{ item.vmdb_private_ip }}"
        groups: [appliance]
      loop: "{{appliance}}"


