- name: VM Based Deployment
  hosts: localhost
  tasks:
    - debug:
        msg: "Starting Deployment..."

- import_playbook: infrastructure.yml

- import_playbook: configuration.yml

#- import_playbook: ibmcloud/create_lb.yml
#  when: provider == "ibmcloud"

- name: VM Based Deployment
  hosts: localhost
  tasks:
    - debug:
        msg: "Deployment completed!!"