---
- name: VM Based Infrastructure
  hosts: localhost
  tasks:
    - debug:
        msg: "Starting Infrastructure creation..."

- import_playbook: ibmcloud/main.yml
  when: provider == "ibmcloud"

- import_playbook: add_host.yml

- name: VM Based Infrastructure
  hosts: localhost
  tasks:
    - debug:
        msg: "Infrastructure creation completed!!"




