---
- name: VM Based deployment
  hosts: localhost
  tasks:
    - debug:
        msg: "Starting Playbook execution"

- import_playbook: initialize_host.yml

- import_playbook: ibmcloud/main.yml
  when: provider == "ibmcloud"

- import_playbook: add_host.yml

- name: Get host file contents
  hosts: localhost
  tasks:
    - debug: msg="the value of inventory is {{lookup('file', 'hosts/miq-inventory') }}"

    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']



