---
- name: Add Tag to VM
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "{{ lookup('env', 'VMWARE_HOST') }}"
    vcenter_user: "{{ lookup('env', 'VMWARE_USER') }}"
    vcenter_pass: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
  tasks:
    - name: Login into vCenter and get cookies
      uri:
        url: https://{{ vcenter_server }}/rest/com/vmware/cis/session
        force_basic_auth: yes
        validate_certs: no
        method: POST
        user: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
      register: login
    - name: Get Tag
      uri:
        url: https://{{ vcenter_server }}/rest/com/vmware/cis/tagging/tag/id:urn:vmomi:InventoryServiceTag:5722a5e4-1cbc-4e63-ba5f-2fb1f8bd0177:GLOBAL
        force_basic_auth: yes
        validate_certs: no
        method: GET
        headers:
          Cookie: "{{ login.set_cookie }}"
      register: tags
    - name: Assign Tag to VM
      uri:
        url: https://{{ vcenter_server }}/rest/com/vmware/cis/tagging/tag-association?~action=attach-multiple-tags-to-object
        force_basic_auth: yes
        validate_certs: no
        method: POST
        headers:
          Cookie: "{{ login.set_cookie }}"
          Content-Type: "application/json"
        body: |
              {
                "object_id": {
                  "id": "{{ vm_moid }}",
                  "type": "VirtualMachine"
                },
                "tag_ids": [
                  "urn:vmomi:InventoryServiceTag:5722a5e4-1cbc-4e63-ba5f-2fb1f8bd0177:GLOBAL"
                ]
              }
        body_format: json
      register: assignTags