---

- name: Install php packages 
  yum:
    name: php
    state: present

- name: Install php-mysql packages 
  yum:
    name: php-mysql
    state: present

- name: Create /etc/my.cnf
  template:
    src: ../../templates/index.php
    dest: /var/www/html/index.php
    owner: root
    group: root
    mode: 0644
    backup: true
