---
- name: Create File
  gather_facts: no
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:

    - name: Run command inside a virtual machine
      community.vmware.vmware_vm_shell:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
        vm_username: "{{ vm_username }}"
        vm_password: "{{ vm_password }}"       
        vm_id: "{{ vm_name }}"
        vm_shell: "/bin/echo"
        vm_shell_args: " -e 'NAME=eth0\nGATEWAY=10.155.124.65\nDNS1=10.154.23.131\nDNS2=8.8.8.8\nDEVICE=eth0\nONBOOT=yes\nUSERCTL=no\nBOOTPROTO=static\nNETMASK=255.255.255.192\nIPADDR=10.155.124.106\nPEERDNS=no\ncheck_link_down() {\nreturn 1;\n}\n' > ifcfg-eth0 "
        vm_shell_cwd: "/etc/sysconfig/network-scripts"
      delegate_to: localhost
      register: shell_command_output
      
    - name: Set the state of a virtual machine to reboot-guest
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        name: "{{ vm_name }}"
        state: reboot-guest
      delegate_to: localhost
      register: deploy