---
- name: Create File
  gather_facts: no
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Run command inside a virtual machine
      community.vmware.vmware_vm_shell:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
        vm_id: "{{ vm_name }}"
        vm_shell: "/bin/echo"
        vm_shell_args: " Hello > /tmp/hello.txt"
        vm_shell_cwd: "/tmp"
      delegate_to: localhost
      register: shell_command_output