---
- name: Create File
  gather_facts: no
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:

    - name: Run command inside a virtual machine
      community.vmware.vmware_vm_shell:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
        vm_username: "{{ vm_username }}"
        vm_password: "{{ vm_password }}"       
        vm_id: "{{ vm_name }}"
        vm_shell: "/usr/bin/yum"
        vm_shell_args: " -y httpd "
        vm_shell_cwd: "/tmp"
      delegate_to: localhost
      register: shell_command_output
      
