---
- name: Add a disk to already existing VM
  gather_facts: no
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Getting information about VM {{ vm_name }}
      vmware_guest_disk_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
      register: disk_info