---
- name: Create IBM Cloud VPC VSI
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Get Resource group in IBM Cloud
      ibm_resource_group_info:
        name: "{{ resource_group_name }}"
        region: "{{ region }}"
        ibmcloud_api_key: "{{ provider_apikey }}"
      register: resource_group_output

    - name: Save Resource group Id
      set_fact:
        cacheable: True
        resource_group_id: "{{ resource_group_output.resource.id}}"

    - name: Create VPC
      ibm_is_vpc:
        name: "{{ name_prefix }}-vpc"
        resource_group: "{{ resource_group_id }}"
        default_security_group_name: "{{ name_prefix }}-security-group"
        default_routing_table_name: "{{ name_prefix }}-routing-table"
        tags: "{{ tag }}"
        state: available
        id: "{{ vpc.id | default(omit) }}"
        region: "{{ region }}"
        ibmcloud_api_key: "{{ provider_apikey }}"
      register: vpc_create_output

    - name: Save VPC as fact
      set_fact:
        cacheable: True
        vpc: "{{ vpc_create_output.resource }}"


