---
- name: Print Linux distribution
  debug:
    msg: "{{ ansible_distribution }} version {{ ansible_distribution_major_version }}"

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: Generate /etc/hosts file
  template:
    src: ../templates/hosts.j2
    dest: /etc/hosts

- name: Include tasks for packages installation on specific distribution
  include_tasks: "packages/redhat.yml"


