---
- name: VM Based deployment
  hosts: localhost
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: configurations/group_vars/all/vars.yml
    - name: Add host to inventory
      add_host:
        hostname: 10.241.65.120
        groups: master_primary_db
        private_ip: 10.241.65.120
        miq_appliance_hostname: auto-master-vmdb-01
        miq_cluster_node_number: 2
        primary_host_ip: 10.241.65.120
        cfme_master_region: 88
        replication_type: primary
        miq_db_disk: /dev/vdb

    - name: Add host to inventory UI
      add_host:
        hostname: 10.241.65.121
        groups: master_primary_appliance
        private_ip: 10.241.65.121
        miq_appliance_hostname: auto-master-ui-01
        vmdb_private_ip: 10.241.65.120

    - name: Add host to inventory UI
      add_host:
        hostname: 10.241.128.5
        groups: vmdb_appliance
        private_ip: 10.241.128.5
        miq_appliance_hostname: auto-master-vmdb-02
        miq_cluster_node_number: 3
        primary_host_ip: 10.241.65.120
        cfme_master_region: 88
        replication_type: standby
        miq_db_disk: /dev/vdb

    - name: Add host to inventory UI
      add_host:
        hostname: 10.241.128.8
        groups: ui_appliance
        private_ip: 10.241.128.8
        miq_appliance_hostname: auto-master-ui-02
        vmdb_private_ip: 10.241.65.120

- import_playbook: configurations/miq-config-test.yml 
