#- hosts: localhost
#  vars_files:
#      - group_vars/all/vars.yml
#  tasks:
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}" 
    
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_appliance') }}" 


## All hosts
- hosts: master_primary_db
  become: yes
  vars:
    ansible_ssh_pass: "{{ cfme_new_root_pw }}"
    ansible_ssh_user: root

  tasks: 
  - name: Synchronize time
    become: yes
    service:
      name: 'chronyd'
      enabled: 'yes'
      state: 'started'
    tags: 'chrony-service'

  - name: Restart hostnamectl service
    command: systemctl restart systemd-hostnamed
  

  - name: Set hostname command
    command: hostnamectl set-hostname testvm123

  - name: Set hostname
    become: yes
    hostname: 
      name: testvm999



