#- hosts: localhost
#  vars_files:
#      - group_vars/all/vars.yml
#  tasks:
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}" 
    
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_appliance') }}" 


## All hosts
- hosts: master_primary_db
  become: yes
  tasks: 
  - name: Synchronize time
    service:
      name: 'chronyd'
      enabled: 'yes'
      state: 'started'
    tags: 'chrony-service'

  - name: Dispay Host name
    command: hostname
    register: hostnameMsg

  - debug: msg="{{ hostnameMsg }}"

  - name: Create DIR
    command: mkdir /tmp/test99



