# Ansible playbook that uses appliance_console_cli, plus existing
# Ansible modules, to provision a freshly deployed CloudForms manageIQ appliance.
#

# this play performs initial sysadmin for newly created CFME appliances
# we set a non-default root password, install a public key for ansible,

- hosts: localhost
  vars_files:
      - group_vars/all/vars.yml
  tasks:
    - include_tasks: reset-default-passwor.yml
      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}" 

## All hosts
- hosts: all
  vars:
    ansible_ssh_pass: "{{ cfme_new_root_pw }}"

  tasks: 
  - name: Set hostname
    hostname: 
      name: "{{ miq_appliance_hostname }}" 

## primary master VMDB appliance
- hosts: master_primary_db
  vars:
    ansible_ssh_pass: "{{ cfme_new_root_pw }}"

  tasks:
    - name: Reboot
      reboot:

    - name: Enable database server
      ansible.builtin.shell:
       cmd: systemctl enable evmserverd
