#- hosts: localhost
#  vars_files:
#      - group_vars/all/vars.yml
#  tasks:
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}" 
    
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_appliance') }}" 


## All hosts
- hosts: master_primary_db
  become: yes
  vars:
    ansible_ssh_pass: "{{ cfme_new_root_pw }}"
    ansible_user: root

  tasks: 
  - name: Synchronize time
    become: yes
    service:
      name: 'chronyd'
      enabled: 'yes'
      state: 'started'
    tags: 'chrony-service'
    delegate_to: localhost

  - name: Dispay Host name
    command: hostname
    register: hostnameMsg
    delegate_to: localhost

  - debug: msg="{{ hostnameMsg }}"
    delegate_to: localhost


  - name: Create DIR
    command: mkdir /tmp/test99
    delegate_to: localhost



