#- hosts: localhost
#  vars_files:
#      - group_vars/all/vars.yml
#  tasks:
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}" 
    
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_appliance') }}" 


## All hosts
- hosts: localhost
  become: yes
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: bWFuYWdlaXE=
  tasks: 
  - name: SSH and read the file content
    expect:
      command: ssh  root@169.63.179.101
      responses:
        (?i)password: bWFuYWdlaXE=
        (?i)root@localhost: mkdir /tmp/test222 && exit 
    register: output 

  - name: Printing the output 
    debug : 
      msg: '{{ output.stdout }}'      




