#- hosts: localhost
#  vars_files:
#      - group_vars/all/vars.yml
#  tasks:
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_db') }}" 
    
#    - include_tasks: reset-default-passwor.yml
#      loop: "{{ query('inventory_hostnames', 'master_primary_appliance') }}" 


## All hosts
- hosts: 10.241.65.79
  become: yes
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: bWFuYWdlaXE=
  tasks: 
  - name: Dispay Host name
    command: hostname
    delegate_to: 169.63.179.101
    register: hostnameMsg 

  - debug: msg="{{ hostnameMsg }}"

  - name: Create DIR
    command: mkdir /tmp/test999



